common:
  lables:
    fargate: "false"
frontend:
  enabled: true
  image: "efrat19/shifts-scheduler:latest"
  probes:
    enabled: true
    path: /healthz
    timeout: 3
  env:
  - name: SLACK_SIGNING_SECRET
    value: your-slack-signing-secret
  - name: SLACK_WEBHOOK_URL
    value: your-slack-webhook-url
  service:
    port: 80
    targetPort: 8080
  ingress:
    enabled: true
    hosts:
    - host: shifts-scheduler.yourdomain.io
      paths: ["/"]
    annotations:
      kubernetes.io/ingress.class: nginx-nodeport
  hpa:
    replicaMin: 1
    replicaMax: 3
