# Default values for antibot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
common:
  lables:
    fargate: "false"

secrets: []

networkPolicy:
  enabled: false

preupgrade:
  enables: false
  command: []

backend:
  enabled: false
  hostAliases: []
  #- ip: 0.0.0.0
  #  hostnames:
  #  - name: "aaaaaa"
  #  - name: "bbbb"
  #- ip: 1.1.1.1
  #  hostnames:
  #  - name: "aaaaaa"
  image: ""
  imagePullPolicy: IfNotPresent

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: false
  env: []

  volumes: []

  volumeMounts: []

  probes:
    enabled: false
    path: "/"
    timeout: 3

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: []

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  enableResources: true
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
    
  hpa:
    enabled: true
    replicaMin: 2
    replicaMax: 10
    targetAverageUtilization: 70

  nodeSelector: {}

  tolerations: []

  affinity: {}

frontend:
  enabled: false
  image: ""
  imagePullPolicy: IfNotPresent
  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  
  probes:
    enabled: false
    path: "/"
    timeout: 3

  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: false
    headers:
      enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: {}
  
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  enableResources: true  
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
    
  hpa:
    enabled: true
    replicaMin: 2
    replicaMax: 10
    targetAverageUtilization: 70
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}

antibot:
  enabled: false
  image: ""
  imagePullPolicy: IfNotPresent
  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  
  enableConfig: true
  ss2_config: |
    ss2_config.json file goes here 

  env:
  - name: ROOT_SERVICE
    value: 
  - name: ROOT_PORT
    value: 
  - name: API_SERVICE
    value: 
  - name: API_PORT
    value:   
  - name: CANARY
    value: never # nerver/always

  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: {}
  
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  probes:
    enabled: false
    path: "/"
    timeout: 3

  enableResources: true
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}

  hpa:
    enabled: true
    replicaMin: 2
    replicaMax: 10
    targetAverageUtilization: 70

