{{- if .Values.antibot.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master.fullname" . }}-antibot
  labels:
    app.kubernetes.io/name: {{ include "master.name" . }}-antibot
{{ include "master.labels" . | indent 4 }}
{{ toYaml .Values.common.lables | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "master.name" . }}-antibot
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.antibot.replicas }}
  replicas: {{ . }}
{{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "master.name" . }}-antibot
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ toYaml .Values.common.lables | indent 8 }}
    spec:
    {{- with .Values.antibot.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.antibot.enableConfig }}
      volumes:
      - name: ss2-config
        configMap:
          name: {{ template "master.fullname" . }}-antibot-ss2-config
    {{- end }}
      containers:
        - name: {{ .Release.Name }}-antibot
          image: "{{ .Values.antibot.image }}"
          imagePullPolicy: {{ .Values.antibot.imagePullPolicy }}
          env:
          {{- toYaml .Values.antibot.env | nindent 10 }}
          {{- if .Values.antibot.enableConfig }}
          volumeMounts:
          - name: ss2-config
            mountPath: /usr/local/nginx/lua/ss2_config.json
            subPath: ss2_config.json
            readOnly: true
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.antibot.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.antibot.probes.path }}
              port: http
            timeoutSeconds: {{ .Values.antibot.probes.timeout }}
          readinessProbe:
            httpGet:
              path: {{ .Values.antibot.probes.path }}
              port: http
            timeoutSeconds: {{ .Values.antibot.probes.timeout }}
          {{- end }}
          {{- if .Values.antibot.enableResources }}
          resources:
            {{- toYaml .Values.antibot.resources | nindent 12 }}
          {{- end }}
{{- if .Values.antibot.extraContainers }}
{{ toYaml .Values.antibot.extraContainers | indent 8}}
{{- end }}
      {{- with .Values.antibot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.antibot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.antibot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
