{{- if .Values.backend.enabled -}}
{{- if .Values.backend.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "master.fullname" . }}-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "master.fullname" . }}-backend
  minReplicas: {{ .Values.backend.hpa.replicaMin }}
  maxReplicas: {{ .Values.backend.hpa.replicaMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.backend.hpa.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.backend.hpa.targetAverageUtilization }}
{{ with .Values.backend.hpa.additionalMetrics }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
