{{ range .Values.secrets }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
{{ include "master.labels" $ | indent 4 }}
spec:
  backendType: secretsManager
  data:
  {{ range .data }}
    - key: {{ .key }}
      name: {{ .name }}
{{ end }}
{{ end }}