{{- if .Values.frontend.enabled -}}
{{- if .Values.frontend.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "master.fullname" . }}-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "master.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.hpa.replicaMin }}
  maxReplicas: {{ .Values.frontend.hpa.replicaMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.frontend.hpa.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.frontend.hpa.targetAverageUtilization }}
{{- end }}
{{- end }}