{{- if .Values.preupgrade.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "master.fullname" . }}-preupgrade
  labels:
{{ include "master.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "master.fullname" . }}-preupgrade
      labels:
{{ include "master.labels" . | indent 10 }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ include "master.fullname" . }}-preupgrade
        image: {{ .Values.backend.image }}
        {{- if .Values.preupgrade.command }}
        command:
{{ toYaml .Values.preupgrade.command | indent 8 }}
        {{- end }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        {{- toYaml .Values.backend.env | nindent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.backend.service.targetPort }}
            protocol: TCP
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}